version: '3.8'

services:
  smtp-json-server:
    build:
      context: .
      dockerfile: Dockerfile
    # Uncomment and modify this line to use your Docker Hub image
    # image: your-dockerhub-username/smtp-json-server:latest
    container_name: smtp-json-server
    ports:
      - "8025:8025"
    environment:
      - SMTP_HOST=0.0.0.0
      - SMTP_PORT=8025
      - WEBHOOK_URL=https://your-webhook-endpoint.com/api/emails
      - API_KEY=your_api_key_here
      - LOG_LEVEL=INFO
      - TZ=UTC
    restart: unless-stopped