FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY node/package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY ./node .

# Expose SMTP port
EXPOSE ${SMTP_PORT:-8025}

# Start the application
CMD ["node", "index.js"]